name: CI

on:
  push:
    branches: [ master ]
  # TODO: temporary for faster tests, restore!
  # pull_request:
  #   branches: [ master ]

jobs:
  android:
    # runs-on: ubuntu-latest
    runs-on: macos-latest

    # outputs:
    #   built-apk: ${{ steps.buildApk.outputs.apkPath }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Cache Android build outputs
        uses: actions/cache@v4
        with:
          path: |
            build/app/outputs/flutter-apk/
          key: ${{ runner.os }}-android-build-outputs-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-build-outputs-


      # - name: Enable KVM
      #   run: |
      #     echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      #     sudo udevadm control --reload-rules
      #     sudo udevadm trigger --name-match=kvm
      
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29
          # key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          # api-level: ${{ matrix.api-level }}
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          emulator-boot-timeout: 20000
          # script: echo "Generated AVD snapshot for caching."
          script: ./gradlew connectedCheck
          
      # - name: run tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
          # script: ./gradlew connectedCheck

      # - name: run tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     # api-level: ${{ matrix.api-level }}
      #     api-level: 29
      #     arch: arm64-v8a
      #     force-avd-creation: false
      #     emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     disable-animations: true
      #     script: ./gradlew connectedCheck

      - name: Cache JDK
        uses: actions/cache@v4
        with:
          path: |
            ~/jdk
          key: ${{ runner.os }}-jdk-${{ hashFiles('**/.java-version') }}  # Assuming you specify the JDK version in a .java-version file
          restore-keys: |
            ${{ runner.os }}-jdk-

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # This is Eclipse Temurin, you can change it to your preferred distribution
          # cache: 'gradle'  # This option automatically caches the Gradle wrapper and dependencies
          cache: 'gradle'  # This option automatically caches the Gradle wrapper and dependencies

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check Flutter version
        run: flutter doctor -v
      - name: Get all packages Flutter
        run: flutter pub get
      - name: Flutter Build debug APK
        id: buildApk
        run: flutter build apk --debug --dart-define=FORCE_CAPTURE_MODE=false

      # - name: Upload APK
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: App APK
      #     path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: Install TestSweets
        run: |
          brew tap filledstacks/tap
          brew install testsweets
      
      # - name: Start Emulator # TODO: Currently we have to find the Alternative for this only
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     arch: arm64-v8a
      #     emulator-boot-timeout: 20000
      #     script: ./gradlew connectedCheck

      # - name: TestSweets Authenticate
      #   run: testsweets authenticate -e ${{ secrets.TESTSWEETS_EMAIL_ACCOUNT }} -p ${{ secrets.TESTSWEETS_PASSWORD }}

      - name: List Connected Emulators
        run: |
          adb devices

      - name: Run TestSweets Tests
        run: testsweets run -p $project_id -a $app_path -e $email -w $password
        env:
          project_id: qA5ua2TOgxBtMGcSVBGE
          app_path: build/app/outputs/flutter-apk/app-debug.apk
          config_name: "Config Name"
          email: ${{ secrets.TESTSWEETS_EMAIL_ACCOUNT }}
          password: ${{ secrets.TESTSWEETS_PASSWORD }}
  ios:
    runs-on: macos-14 # use macos-14 insted of macos-latest-large as that is based on M1 (  https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#:~:text=N/A-,macOS,N/A,-Standard%20GitHub%2Dhosted ) 

    # outputs:
    #   built-apk: ${{ steps.buildApk.outputs.apkPath }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache CocoaPods dependencies
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check Flutter version
        run: flutter doctor -v
        
      - name: Get all packages Flutter
        run: flutter pub get
        
      - name: Flutter Build debug IPA
        id: buildIpa
        run: flutter build ios --debug --simulator --no-codesign --dart-define=FORCE_CAPTURE_MODE=false

      # - name: Upload APP
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: App APP
      #     path: build/ios/iphonesimulator/Runner.app


      - name: Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: Install TestSweets
        run: |
          brew tap filledstacks/tap
          brew install testsweets

      - name: 'Print the devices list'
        run: xcrun simctl list devices available --json

      # install jq - cli tool for json querying
      # retrieve the device .udid to use in tests and store it in env var
      - name: 'Set Up Simulator UUID'
        run: |
          brew install jq &&
          IOS_SIM_UUID=$(xcrun simctl list devices available --json | jq -r '.devices."com.apple.CoreSimulator.SimRuntime.iOS-17-0"[] | select(.name == "iPhone 14") | .udid') &&
          echo "IOS_SIM_UUID=$IOS_SIM_UUID" >> $GITHUB_ENV
      
      - name: 'Print Selected UUID'
        run: echo $IOS_SIM_UUID
      
      - name: Start Emulator and Run TestSweets
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14 Pro'
      
      # - name: TestSweets Authenticate
      #   run: testsweets authenticate -e ${{ secrets.TESTSWEETS_EMAIL_ACCOUNT }} -p ${{ secrets.TESTSWEETS_PASSWORD }}

      - name: Run TestSweets Tests
        # run: testsweets run -p $project_id -a $app_path -c $config_name -e $email -w $password
        run: testsweets run -p $project_id -a $app_path -e $email -w $password
        env:
          project_id: qA5ua2TOgxBtMGcSVBGE
          app_path: build/ios/iphonesimulator/Runner.app
          config_name: "Config Name"
          email: ${{ secrets.TESTSWEETS_EMAIL_ACCOUNT }}
          password: ${{ secrets.TESTSWEETS_PASSWORD }}
          
